version: "3"

services:
  frontend:
    # build: .
    image: eeacms/bise-frontend:develop
    ports:
    - "${FRONTEND:-3000}:3000"
    environment:
      RAZZLE_INTERNAL_API_PATH: "http://backend:8080/Plone"
      RAZZLE_DEV_PROXY_API_PATH: "http://backend:8080/Plone"
    volumes:
    - ./src/addons:/app/src/addons
    depends_on:
      - backend
  
  backend:
    build: ./bise-backend/
    ports:
    - "${BACKEND:-8080}:8080"
    environment:
      SITE: "Plone"
    volumes:
      - data:/data

volumes:
  data: {}
